import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import TopNav from "./_components/topnav";

export const metadata = {
  title: "Chen Gallery",
  description: "Generated by chen237",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>

    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="font-sans flex flex-col gap-4">
        <TopNav />
        {children}
        </body>
    </html>
    </ClerkProvider>

  );
}
